sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-136
env:
  global:
    -
      # LTD_AWS_ID
      secure: pRtkKpl8RAA5bQy6ERsyChdr65nEOSuEA+R+Zfw7pVAqfS/7NkUjF1QtyGLZX+PQnrzWXkwBTADAzRQkyrFGnr4uAypyp8vX5CD09JbNpF4EOQq3MlLblMD8qAXEb0eXtBQzEUpr44NdOJ2ZxwR8hLKX6Q5Ka0QaEugvOtvwTZSscf0aQvYzj0jz9b0FywV9NvgNtFQd5gb/aUlUaC121/E8p0FlKV0X5q3vykAEAHvlMVghm7Z/xaLuxOf6AUNWsvr72YM9tU9emCln0gzzfNYBU0l07WM1iFrZ/B+e5zbEtgjHBX0tDCteiRDZl/sg8gj3OO66nxD8rtHm+19r23GsgRqfqEZib55WAr5UbkzweDfj24xhiRMeelThZkwPLBk86dgxZ57yZgVLN2qEmRyq426zpXWJkwIvje5nvH+g6Ybfi/0v0RwG6Dm3vZfmEs0oSeWbEfNWg46xCX4rSKvMWz/40MIhs4adJrNraqI9D93328zhMfVrJ7rQ709+wWDCkQSIpG5IqaQmySAt+JdOwP21iMLidaMv2OtcS4FYlaG3g0Q6hQbOMLh4Y0b47XVSEmPPT7bL6B5UpzGucows5PDo6KCDCLoWJ38taYIdASnEUaAHsnJNbepKXYQqY57fC5GQGX6iB0zyqeZN1oeNwQ3PwnO5BBf0thN+xTE=
    -
      # LTD_AWS_SECRET
      secure: Sbsui8Biuy8nm2pDH8G6meOQ3f4GygtAB8vXfI57Wn/bi3Q9kxq7qgi042YazPkan1vV6FmnRWBDcOev8TyzUtf9PCfLc+j+27KI64W5883iMQbUijvblEA1YvBFVcHJ9nXVSQhj044K4irKgz4GQNxtBX9OIromB41uTerHWXbxDqpCXb+HRI+CziVKqGPjeWYcm49m9AWGLXTEaYT5StubcwHcKLlboLmfiF8nkJZFTWTzIoXcPlWlhqZkgu6euPGu3+iGyvb/LFLY32fJ/fJ6r2I8JeCl72pnlnYV8Uslrps0gKd+grC7DzKUvMmA0qQAb4YFqOnZbEpyoui3MrhgxvBH//fz8dV3iRj7sK1WAZRac3scXp9Bf8QubbtDRJ4W4cB7Hrjiw7OV8fALNZ3KdwsIUOGfrVMXfIozFnGD7Qpo7WcJ3SYXupT3XgoAnO12BWU7Iqqqm4H9m1pYpw+N0S6pLm7EVJb2bhtF1LMADUh7CbPG6sVEhpFCdAX6okUwLftHY82CLZHxxTY54KrWm8JVNZYUKun/0hwIclJ4bFnq5AyJC9uZaPTQBm64pC6zBMlrp6iNMkiQpqtpyYh4Jgum314sx03DlKuYYPMlur5hmb4BK7o1hr0bmpD5opgUOK2GlEC8iaee/CD1K1PFhylNl/wOSxbZsVXLuQA=
    -
      # LTD_USERNAME
      secure: U6oJr3eWFbR0OiiemAeGI0sYYgQHDwSRRNlM5OhnydmIX/4HsAScmABoMQ63tJ7hsA/E3OwdFdt19sMfZBAqu6TJdG90NONyp0cD2DYUblbCwfDKHk0owEp8BqDu1GXLsYmpdMaK4snkFzwQlcyyG6wPHO7MvsxTwNdkwnRkiFnh2f1vxRSi45Nz49ZfKFTzCceRfTATVgXA8Lu/e03weh6ll6ca2Lr80f3WmLaJ893ptDlSUYt5iXvcXZkbkaLOFJVqLqFt0ngVhY4txaCnAUxBo+TOrOTw1xwF3R//p/YNY2IAIqorkPAIItTKs1X9GVVTxMLh9IYXEZbadelhtPQIZIDJ0Cn6aCW1Je2hd2xx0lyo9MDrRAUad/MgjaxQf/sAnhJvvItlV3LmPrODAkEJdhUgdyWaZkBGSlI09nZJl0DgL+z/2Mn6fY827kyM3H5cu6rLVwX+iUXMBdLXkR+X0z/zx5IkYTuaQri8mgJof+htDAxkm0OSTWg/BjasWc9320On6C8odzDABez0nXpN/sxLCO8OwrnR6Kr0eZtxLoaV2aZQ3gL+r89JYQ2xMZIvYa//xu2O4hB9ns3FCCSNF8bbanLSsdolyO9yqavtEPRG+QbO4vfcn7Ay2dAzu/1IjVnrJ0H0rD2nBSvj+QKWMdBU1OT/ew59ChJ6tq4=
    -
      # LTD_PASSWORD
      secure: Vh1H/f3nfN2crNXQ13iMLCy1jEyE/6/ZJ0BiOp+bk7GaT3EDc3DMlAB4Dvn2BQuXnpkIrBiWgVeXrC7CXyFvI9e//mhI2GP4QJJGkBMGY5B949MduMl33TU4kDsksM7aUJHH1A4wHiA8AAmvhHu2odrY6pCrtPXQVl8i3lKrSlkfYYY6ATlSo1JKuE18RsQXWgFwPpYXLsyWHU4ywyJbecRmRzB1G6PND9H5wAat+UKK9BfRPOG89ctvH2dfuY5dcFnXFmYdcGMcbZwcaBSp9r5Fw9kkqJP4qv8bwTJO7XhcpmmF/GWzNoOBP4fLZodWSGokCQXAKXzHnEQZ9IFsNmoODbd6E2WQjEZj6QyKpsdCYLSekdE4zkNgq1Bq8O2xYOsussF5T4dwBpbukdG5LDEz9koepWPQc1nodhRZgmcGZG2bJtaqWCekP2HBq93LKBEaQgVRbtOyaACyT2E0jZqLZDM9d3JjLPywLZXBBIOy0q7mgFlQvGkBDy++76KAq+ifuZhXjN24cu5tLjK21EYBh+fMKoqCiu4IoqBfNtSu2kmET00L1FEGWdewy56HnI8D9sx9Ldy2q8yJX44fsacbw0gLu6JIX2+amRjxXV9ScuM5Jj6w2pi9O3qNTIH8C+pUv0h+W20Z1bm3exd/C55/H/KA9bNm1+Kd3lroCBI=
